### ISSUE TITLE
Created at & Expires on timestamp is incorrect

### ISSUE THREAD

**Issue by kriticalflare** [Mithil467/Mitbin#1]
The timestamps in question are using the server timezone rather than the local client timezone

**Comment by Mithil467** [comment]
Thanks @kriticalflare for pointing it out!

I had a hard time trying to show the time from the user's timezonel. So I have just made it clear that it will be using the UTC time by formatting the date a bit differently. I know this is not the best solution, I will keep trying to achieve it in my upcoming development period :)
